const operas = [
    // --------------------
    {
        title: "河洛歌仔戲",
        list: "https://www.youtube.com/playlist?list=PL07k_cSleUnxBLFo-UDqiykVNE6G1PhF_",
        thumbnail: "https://img.youtube.com/vi/KDnxWLSqtEw/mqdefault.jpg",
        source: "影音娛樂台Fujit Music",
    },
    // --------------------
    {
        title: "明華園歌仔戲——新加坡演出",
        list: "https://www.youtube.com/playlist?list=PL2LuMo86kJBV8_EdrgoFrjTVnAOBhq_Ov",
        thumbnail: "https://img.youtube.com/vi/8lKBQ-sCSzM/mqdefault.jpg",
        source: "青森",
    },
    // --------------------
    {
        title: "舞台劇／電視劇／黑貓大舞台",
        list: "https://www.youtube.com/playlist?list=PL_dn5H-1Kw6GQDCo2EflCByC-KhniA28i",
        thumbnail: "https://img.youtube.com/vi/GXqqb87LiYU/mqdefault.jpg",
        source: "中華傳統文化",
    },
    // --------------------
    {
        title: "國立臺灣戲曲學院歌仔戲學系——高職部對外演出",
        list: "https://www.youtube.com/playlist?list=PLVz8JDnijbySHQ-tdx37WXSUV_axw5-rD",
        thumbnail: "https://img.youtube.com/vi/w_mm4-N1ih8/mqdefault.jpg",
        source: "國立臺灣戲曲學院歌仔戲學系",
    },
    {
        title: "國立臺灣戲曲學院歌仔戲學系——高職部畢業公演",
        list: "https://www.youtube.com/playlist?list=PLVz8JDnijbyTWVfaLsb_ohW5DBRtdALod",
        thumbnail: "https://img.youtube.com/vi/v4OZlZF5cb4/mqdefault.jpg",
        source: "國立臺灣戲曲學院歌仔戲學系",
    },
    {
        title: "國立臺灣戲曲學院歌仔戲學系——專科時期回顧",
        list: "https://www.youtube.com/playlist?list=PLVz8JDnijbyQ8qDhodZoKoCCTWHLNiNq5",
        thumbnail: "https://img.youtube.com/vi/f7vka6ztJqE/mqdefault.jpg",
        source: "國立臺灣戲曲學院歌仔戲學系",
    },
    {
        title: "國立臺灣戲曲學院歌仔戲學系——學院部對外演出",
        list: "https://www.youtube.com/playlist?list=PLVz8JDnijbyTgI7fKZsldR5_emc2rM2gR",
        thumbnail: "https://img.youtube.com/vi/QZY9WebwZk8/mqdefault.jpg",
        source: "國立臺灣戲曲學院歌仔戲學系",
    },
    {
        title: "國立臺灣戲曲學院歌仔戲學系——學院部畢業製作",
        list: "https://www.youtube.com/playlist?list=PLVz8JDnijbyTyDGk_bmzNT43NnVOJs6B7",
        thumbnail: "https://img.youtube.com/vi/jvTC-g2tGIc/mqdefault.jpg",
        source: "國立臺灣戲曲學院歌仔戲學系",
    },
    // --------------------
    {
        title: "薛仁貴征東",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UpTyH2jBjLbH_8g71eXU-VA",
        thumbnail: "https://img.youtube.com/vi/ASj5Fujwzco/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "薛平貴",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UpfozIrkw9wFE8KO18UYRzt",
        thumbnail: "https://img.youtube.com/vi/DroSd0WFy4M/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "薛丁山",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UqAd4z9OUNrQknIXO8BrL3F",
        thumbnail: "https://img.youtube.com/vi/JQJE7Lkq7zs/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "花月正春風",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UrYLtQIQPaJVMh-0gesu0m_",
        thumbnail: "https://img.youtube.com/vi/QiypLZR_FeM/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "楊家將",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28Upil5wEZAafHg4OEJiBXOwQ",
        thumbnail: "https://img.youtube.com/vi/GPDS2MMGN0E/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "萬花樓",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UrNgYp6OM71HSwWiCPfpmx-",
        thumbnail: "https://img.youtube.com/vi/qiUW2Tm9U8o/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "梁山伯與祝英台",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28Uoo4MFGqNUPslRptv7ObQ1w",
        thumbnail: "https://img.youtube.com/vi/gfzhy1uR1_s/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "鐵扇留香",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UpBqrcWv-hqtbdv5h8NOnQn",
        thumbnail: "https://img.youtube.com/vi/Rx2yKu-rk_k/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "西江月",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UoTBkcw6sacg38Mo8QoWU0A",
        thumbnail: "https://img.youtube.com/vi/eAmhInah7sA/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "恩怨情天",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UrQV7VyC_xK_GItqu8bGw2-",
        thumbnail: "https://img.youtube.com/vi/d6xl2NvJxto/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "七俠五義",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28Up2quraVTmzo5GKUuCmGx2m",
        thumbnail: "https://img.youtube.com/vi/lrUc2OIkbl8/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "情海斷腸花",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UqNPz5oT_r9mcXzqsDDcHqO",
        thumbnail: "https://img.youtube.com/vi/i13qMPEKYGA/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "年羹堯新傳",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28UoKcS741Mt15XhAlTNK7DCH",
        thumbnail: "https://img.youtube.com/vi/k2enqRPs-Eg/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "狸貓換太子",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28Uo5OWtVXJeOqVWWtRHO8_W5",
        thumbnail: "https://img.youtube.com/vi/uBlcdnhdnmw/mqdefault.jpg",
        source: "台視",
    },
    {
        title: "虎膽義魄",
        list: "https://www.youtube.com/playlist?list=PLXu9pYCj28Uo4VPlw-EheS3dKwLLzerh5",
        thumbnail: "https://img.youtube.com/vi/TlukCL1CUmY/mqdefault.jpg",
        source: "台視",
    },
    // ------------------
    {
        title: "陳三五娘",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4dLvF7OsSkes4fsghhKw1qj",
        thumbnail: "https://img.youtube.com/vi/IpF7BhansNQ/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "紅塵客",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4e_w_c8se71moOKF48VOaqz",
        thumbnail: "https://img.youtube.com/vi/ZyOalsFGsr0/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "周公與桃花女",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4eT1PlCVWlCpywtmOBvQ9TA",
        thumbnail: "https://img.youtube.com/vi/2GbCIXS6MZs/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "紅鬃烈馬",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4dwqa-CW3lwPGS0x_X5_ZpT",
        thumbnail: "https://img.youtube.com/vi/C0azsazJnM8/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "巫山一段雲",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4eVnLZWUdK25ACilZehSMaN",
        thumbnail: "https://img.youtube.com/vi/WBrQF-jbDe0/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "龍鳳姻緣",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4f5jnlsBuX41S9yDI-nZWZM",
        thumbnail: "https://img.youtube.com/vi/vsIly8e2W9I/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "秋江煙雲",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4fLlsIe3iXJIDOPZiHHV4Eb",
        thumbnail: "https://img.youtube.com/vi/Q3DH9hXBMTc/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "孟麗君",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4djhQ1BF_MQ3wLTJGWNw6qd",
        thumbnail: "https://img.youtube.com/vi/CH2iTOMDMQc/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "新七俠五義",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4dQvhFLDfq3Cjw3l4B0Efk2",
        thumbnail: "https://img.youtube.com/vi/NuQLqXZeo88/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "洛陽橋",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4cJuYq0jlEhZwZScMrqsgAz",
        thumbnail: "https://img.youtube.com/vi/oL8wIdbjmmQ/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "薛丁山救五美",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4fSeKn4_1WAGpNZ1Wf0twnE",
        thumbnail: "https://img.youtube.com/vi/HwzhniSc2bs/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "蛇郎君",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4dmA_21Nu2GK7o7H9XQjai2",
        thumbnail: "https://img.youtube.com/vi/Jv1Rpehy8TU/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "人面桃花",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4f65DlgdVECbGzoabuB0W4O",
        thumbnail: "https://img.youtube.com/vi/O5t2x2kUFIw/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "彩雲天涯",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4eaLZS4kJiC9mrSDQR_6prJ",
        thumbnail: "https://img.youtube.com/vi/wFZtdGgZBGw/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "金鵰玉芙蓉",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4eEfwhhoh6kDmxwZGn5wDJr",
        thumbnail: "https://img.youtube.com/vi/I4dhnYS0hR0/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "千里姻緣路",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4fBWb72BQNAWn5dq1emn9B3",
        thumbnail: "https://img.youtube.com/vi/4RSyd8yD6b4/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "秋霜燕子飛",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4fmyhlxzvINkRofO86rkd8p",
        thumbnail: "https://img.youtube.com/vi/-_-lGvONRLw/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "伍子胥過昭關",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4eTa8ZKYpYzmjrqK49HTxok",
        thumbnail: "https://img.youtube.com/vi/Ctlw-mb_1fQ/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "鐵膽英豪",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4eSMpLupaWOc3JeaBaqWjX6",
        thumbnail: "https://img.youtube.com/vi/wb2GmkgVaXQ/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "浪子李三",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4cJCVfrXzp2DWju4VbGcoKD",
        thumbnail: "https://img.youtube.com/vi/7jdwjTFd1cQ/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "冉冉紅塵",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4fuZmcwzfdVMKZmwusnJvW3",
        thumbnail: "https://img.youtube.com/vi/sDXefsEEq0g/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "斷腸紅",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4cxcso2tnknKLZwnMd3qANT",
        thumbnail: "https://img.youtube.com/vi/CP2yjTAKsx0/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "孔明三氣周瑜",
        list: "https://www.youtube.com/playlist?list=PL8MwjIpV5cFXbaPNIGfBWWQlu10YXMQ6r",
        thumbnail: "https://img.youtube.com/vi/QR9FJ6j9lHw/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "皇甫少華與孟麗君",
        list: "https://www.youtube.com/playlist?list=PL8MwjIpV5cFVzi1q8q95pYcWUiXYBnNUF",
        thumbnail: "https://img.youtube.com/vi/lc7PAu-cu4I/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "薛平貴與王寶釧",
        list: "https://www.youtube.com/playlist?list=PL8MwjIpV5cFV6QwRN5pB2bTDeE8_q-8aQ",
        thumbnail: "https://img.youtube.com/vi/046zf4dNSfo/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "玉樓春",
        list: "https://www.youtube.com/playlist?list=PL8MwjIpV5cFUJcvEld540FKIVRCeMquMo",
        thumbnail: "https://img.youtube.com/vi/zFrHf3gQLN0/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "一見情",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4eLWyPekZ_aBKrnLpvjzwZ8",
        thumbnail: "https://img.youtube.com/vi/XYOtuAdv5lY/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "灞橋煙柳",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4eei-2SUVH8fto-Ruzb-nTF",
        thumbnail: "https://img.youtube.com/vi/U1dZDx92I20/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "瀟湘夜雨",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4d7ahOBiilav0_YstTCr5MA",
        thumbnail: "https://img.youtube.com/vi/y29mY3zMaA8/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "斷情劍",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4eL5ZmKxnBbu42Bql4QhcJQ",
        thumbnail: "https://img.youtube.com/vi/o74Hx3cGAn4/mqdefault.jpg",
        source: "華視",
    },
    {
        title: "描金扇",
        list: "https://www.youtube.com/playlist?list=PLa81SxfdeV4ccy9O031Baq1aygMQqCbV-",
        thumbnail: "https://img.youtube.com/vi/QQ0xnpgVvA8/mqdefault.jpg",
        source: "華視",
    },
    // ------------------
    {
        title: "寶貝王爺貴千金",
        list: "https://www.youtube.com/playlist?list=PL4NcxDS6A-sK5oGSp8K7kwo37IGn_EsJy",
        thumbnail: "https://img.youtube.com/vi/PIL7EdMLo7M/mqdefault.jpg",
        source: "中視",
    },
    {
        title: "江南四才子",
        list: "https://www.youtube.com/playlist?list=PL4NcxDS6A-sJVVjfKXLzFJmqLnDOXI9pz",
        thumbnail: "https://img.youtube.com/vi/Aea1H3LGeJw/mqdefault.jpg",
        source: "中視",
    },
    {
        title: "正德皇帝遊江南",
        list: "https://www.youtube.com/playlist?list=PL4NcxDS6A-sIGxQ5iaU4-ieydUUBQX3Yv",
        thumbnail: "https://img.youtube.com/vi/uUvtXfSXvpA/mqdefault.jpg",
        source: "中視",
    },
    {
        title: "逍遙公子",
        list: "https://www.youtube.com/playlist?list=PL4NcxDS6A-sKhKC_92gOVKRJwreAB1uD4",
        thumbnail: "https://img.youtube.com/vi/QFi5Sw0Kg7c/mqdefault.jpg",
        source: "中視",
    },
    {
        title: "孟嘗君",
        list: "https://www.youtube.com/playlist?list=PL4NcxDS6A-sJve9I08KxvGUC7-TKOh8MA",
        thumbnail: "https://img.youtube.com/vi/d1zZZvtQELg/mqdefault.jpg",
        source: "中視",
    },
    // ------------------
    {
        title: "英雄殘夢",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSm36XpXCq-4hrfB1S8eGJpy",
        thumbnail: "https://img.youtube.com/vi/40jNoIVebLc/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "李靖與紅拂女",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSn-mIdyF-JTlakBD7FzmdHA",
        thumbnail: "https://img.youtube.com/vi/iYH-f_KubsY/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "皇上難為",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSnHj7G7PaStS4ddEuXL-mh-",
        thumbnail: "https://img.youtube.com/vi/R2NaAsgQ8PA/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "巡案與大盜",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSkisLf7OSu1hzrJgi1aXVyb",
        thumbnail: "https://img.youtube.com/vi/AImBrd-3PEI/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "七品巧縣令",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSl39rfY7m_kU76LA1HEHkbr",
        thumbnail: "https://img.youtube.com/vi/NF49bESd72g/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "擎劍雙驕",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSnjUu1HqEQhq5S5FT-JlkSG",
        thumbnail: "https://img.youtube.com/vi/2n-qm-RGo4s/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "順治與康熙",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSkc7uAUyMT3FqcKtdK8S_UE",
        thumbnail: "https://img.youtube.com/vi/yG7RPCjMa1E/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "打金枝",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSln64nS_FGtf1WLrPQyfZuq",
        thumbnail: "https://img.youtube.com/vi/so3RIsfjGXU/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "精忠報國",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSlat5fI7E2qBxmQ5IxuZorP",
        thumbnail: "https://img.youtube.com/vi/rXpCtUwaS_Y/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "甘國寶過台灣",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSngxODFl2MgNYbZP4BuUUgZ",
        thumbnail: "https://img.youtube.com/vi/SV-P3Sa-_YM/mqdefault.jpg",
        source: "chang yao",
    },
    {
        title: "泥馬渡康王",
        list: "https://www.youtube.com/playlist?list=PLwv2BuH91nSnPBD95K8yxv0pSMBwrgnbM",
        thumbnail: "https://img.youtube.com/vi/5pVA1gWmBcU/mqdefault.jpg",
        source: "chang yao",
    },
    // ------------------
    {
        title: "青山綠水情",
        list: "https://www.youtube.com/playlist?list=PLpqyB2dJz1VeShd7hGq1vcWOcAWfgvyQf",
        thumbnail: "https://img.youtube.com/vi/X5sT__eVAjg/mqdefault.jpg",
        source: "看戲趣",
    },
    {
        title: "王伯東告御狀",
        list: "https://www.youtube.com/playlist?list=PLpqyB2dJz1VfsnDVCttlqRD-5FLOOmFO6",
        thumbnail: "https://img.youtube.com/vi/F0M1WMMFSOU/mqdefault.jpg",
        source: "看戲趣",
    },
    {
        title: "王文英與蘆竹馬",
        list: "https://www.youtube.com/playlist?list=PLpqyB2dJz1VfGmk6l02b4ISG00w3vKUet",
        thumbnail: "https://img.youtube.com/vi/kB5MpIukcUE/mqdefault.jpg",
        source: "看戲趣",
    },
    // ------------------
    {
        title: "大唐風雲錄",
        list: "https://www.youtube.com/playlist?list=PL2DwCvzxG8TP9X9Ztr_WepGj1pvrSqq2I",
        thumbnail: "https://img.youtube.com/vi/p0teeBfcWDA/mqdefault.jpg",
        source: "",
    },
];
